version: '3.9'
services:
  mongo:
    image: mongo:4.4.4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes: 
      - mongo-volume:/data/db
    networks: 
      - backend
  bot:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: ghcr.io/namchee/pleasantcord:latest
    restart: unless-stopped
    env_file:
      - ./.env
    environment: 
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - backend

volumes:
  mongo-volume:
    driver: local

networks:
  backend:
