version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes: 
      - mongo-volume:/data/db
  bot:
    build:
      context: .
      dockerfile: Dockerfile.prof
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo

volumes:
  mongo-volume:
    driver: local
