version: '3.9'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes: 
      - mongo-volume:/data/db
    networks:
      - backend
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: pleasantcord:dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - backend

volumes:
  mongo-volume:
    driver: local

networks: 
  backend:
