name: Build and redeploy the bot

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout to master
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint and fix automatically fixable issues
        run: yarn lint:fix
      - name: Build the files
        run: yarn build
      - name: Register slash commands
        run: node scripts/slash.js
        env:
          DISCORD_ID: ${{ secrets.DISCORD_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      - name: Reload the bot
        run: yarn restart
      