name: Lint and test files

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repository
        uses: actions/checkout@v2.3.3
      - name: Setup NodeJS environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16'
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.1.1
      - name: Install dependencies
        run: pnpm install
      - name: Lint code
        run: pnpm run lint
      - name: Test code
        run: pnpm run test
      - name: Build the code
        run: pnpm run build
