name: Build and redeploy the bot

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout to master
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.1.1
      - name: Install dependencies
        run: pnpm run install
      - name: Lint code
        run: pnpm run lint:fix
      - name: Test code
        run: pnpm run test
      - name: Build the code
        run: pnpm run build
      - name: Reload the bot
        run: yarn restart
      